version: '3'

services:
  raspi-cross:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./build-test:/opt/build-test
    command: /bin/sh -c "while sleep 1000; do :; done"
